version: '3'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: yourStrong(!)Password
        ports:
            - "1433:1433"
    redis:
        image: redis
        ports: 
            - "6379:6379"
