version: '3'
services:
    site:
        build: ./Presentation/Usuarios.Presentation.Angular
        ports: 
            - "4200:80"
        depends_on: 
            - api
    api:
        build: ./Presentation/Usuarios.Presentation.Api
        ports: 
            - "7491:80"
        depends_on: 
            - sqlserver
            - redis
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: yourStrong(!)Password
        ports:
            - "1433:1433"
    redis:
        image: redis
        ports: 
            - "6379:6379"
    
