apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1  
  selector:
    matchLabels:
      dabatase: postgres
  template:
    metadata:
      labels:
        dabatase: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
              claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres:12
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    dabatase: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
